// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: DIVISION/DIVISION.proto

package GrpcServerDivision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DivisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A float32 `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B float32 `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *DivisionRequest) Reset() {
	*x = DivisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DIVISION_DIVISION_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisionRequest) ProtoMessage() {}

func (x *DivisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DIVISION_DIVISION_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisionRequest.ProtoReflect.Descriptor instead.
func (*DivisionRequest) Descriptor() ([]byte, []int) {
	return file_DIVISION_DIVISION_proto_rawDescGZIP(), []int{0}
}

func (x *DivisionRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *DivisionRequest) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

type DivisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float32 `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DivisionResponse) Reset() {
	*x = DivisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DIVISION_DIVISION_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivisionResponse) ProtoMessage() {}

func (x *DivisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DIVISION_DIVISION_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivisionResponse.ProtoReflect.Descriptor instead.
func (*DivisionResponse) Descriptor() ([]byte, []int) {
	return file_DIVISION_DIVISION_proto_rawDescGZIP(), []int{1}
}

func (x *DivisionResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_DIVISION_DIVISION_proto protoreflect.FileDescriptor

var file_DIVISION_DIVISION_proto_rawDesc = []byte{
	0x0a, 0x17, 0x44, 0x49, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x2f, 0x44, 0x49, 0x56, 0x49, 0x53,
	0x49, 0x4f, 0x4e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x44, 0x49, 0x56, 0x49, 0x53,
	0x49, 0x4f, 0x4e, 0x22, 0x2d, 0x0a, 0x0f, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x62, 0x22, 0x2a, 0x0a, 0x10, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x5c,
	0x0a, 0x0f, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x49, 0x0a, 0x0e, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x19, 0x2e, 0x44, 0x49, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x2e, 0x44,
	0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x44, 0x49, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x2e, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x6a, 0x65, 0x73,
	0x68, 0x72, 0x65, 0x64, 0x64, 0x79, 0x74, 0x2f, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_DIVISION_DIVISION_proto_rawDescOnce sync.Once
	file_DIVISION_DIVISION_proto_rawDescData = file_DIVISION_DIVISION_proto_rawDesc
)

func file_DIVISION_DIVISION_proto_rawDescGZIP() []byte {
	file_DIVISION_DIVISION_proto_rawDescOnce.Do(func() {
		file_DIVISION_DIVISION_proto_rawDescData = protoimpl.X.CompressGZIP(file_DIVISION_DIVISION_proto_rawDescData)
	})
	return file_DIVISION_DIVISION_proto_rawDescData
}

var file_DIVISION_DIVISION_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DIVISION_DIVISION_proto_goTypes = []interface{}{
	(*DivisionRequest)(nil),  // 0: DIVISION.DivisionRequest
	(*DivisionResponse)(nil), // 1: DIVISION.DivisionResponse
}
var file_DIVISION_DIVISION_proto_depIdxs = []int32{
	0, // 0: DIVISION.DivisionService.DivisionMethod:input_type -> DIVISION.DivisionRequest
	1, // 1: DIVISION.DivisionService.DivisionMethod:output_type -> DIVISION.DivisionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DIVISION_DIVISION_proto_init() }
func file_DIVISION_DIVISION_proto_init() {
	if File_DIVISION_DIVISION_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DIVISION_DIVISION_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DIVISION_DIVISION_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DIVISION_DIVISION_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DIVISION_DIVISION_proto_goTypes,
		DependencyIndexes: file_DIVISION_DIVISION_proto_depIdxs,
		MessageInfos:      file_DIVISION_DIVISION_proto_msgTypes,
	}.Build()
	File_DIVISION_DIVISION_proto = out.File
	file_DIVISION_DIVISION_proto_rawDesc = nil
	file_DIVISION_DIVISION_proto_goTypes = nil
	file_DIVISION_DIVISION_proto_depIdxs = nil
}
